framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            App\Message\AnalyzeCommentMessage: async
            App\Message\AnalyzeCommentReportMessage: async
            App\Message\AnalyzeLocalUserMessage: async
            App\Message\AnalyzePostMessage: async
            App\Message\AnalyzePostReportMessage: async
            App\Message\AnalyzeUserMessage: async
            App\Message\BanUserMessage: async
            App\Message\ReanalyzePostsMessage: async
            App\Message\RemoveCommentMessage: async
            App\Message\RemovePostMessage: async
            App\Message\RestoreCommentMessage: async
            App\Message\RestorePostMessage: async
            App\Message\SendNotificationAsyncMessage: async
            App\Message\UnbanUserMessage: async
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
